image: gcc

variables:
  BIN_NAME_ONE: stage1.out
  BIN_NAME_TWO: stage2.out


stages:
  - test_style
  - build
  - test_stage1
  - test_stage2


test_style:
  stage: test_style
  script:
    - ./linters/run.sh


build:
  stage: build
  script: 
    - make
  artifacts:
    paths:
      - ${BIN_NAME_ONE}
      - ${BIN_NAME_TWO}



test_stage1:
  stage: test_stage1
  script:
    - ./btests/run.sh ./${BIN_NAME_ONE} --tests-path btests/testcases/stage1
  when: manual

test_stage1_mem:
  stage: test_stage1
  script:
    - apt-get update && apt-get install -y valgrind
    - ./btests/run.sh ./${BIN_NAME_ONE} --memcheck --tests-path btests/testcases/stage1
  when: manual

test_stage2:
  stage: test_stage2
  script:
    - ./btests/run.sh ./${BIN_NAME_TWO} --tests-path btests/testcases/stage2
  when: manual

test_stage2_mem:
  stage: test_stage2
  script:
    - apt-get update && apt-get install -y valgrind
    - ./btests/run.sh ./${BIN_NAME_TWO} --memcheck --tests-path btests/testcases/stage2
  when: manual

