#ifndef PROJECT_STAGE2_INCLUDE_RETCODES_H_
#define PROJECT_STAGE2_INCLUDE_RETCODES_H_

enum Errors {
    ARG_ERR = 1,
    IO_FILE_ERR,
    FULL,
    EXIT
};


#endif  // PROJECT_STAGE2_INCLUDE_RETCODES_H_
